FROM python:3

EXPOSE 8000

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV VIRTUAL_ENV=/opt/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

WORKDIR /TEAM_ASSESSMENT_DJANGO
COPY . /TEAM_ASSESSMENT_DJANGO
COPY requirements.txt /TEAM_ASSESSMENT_DJANGO
RUN pip install -r requirements.txt

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "backend.wsgi:application"]