version: "3.9"

services:
  web:
    container_name: team_assessment_django
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 backend.wsgi:application
    ports:
    - 8000:8000